# Generated by Django 4.2.6 on 2023-10-17 03:39

from django.db import migrations, models
import json


class Migration(migrations.Migration):

    dependencies = [
        ('analitycs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonGenerated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(decoder=json.loads, encoder=json.dumps)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ViewData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('country_of_origin', models.CharField(blank=True, max_length=255, null=True)),
                ('browser_language', models.CharField(blank=True, max_length=255, null=True)),
                ('device_type', models.CharField(blank=True, max_length=255, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=255, null=True)),
                ('screen_resolution', models.CharField(blank=True, max_length=255, null=True)),
                ('time_on_site', models.DurationField(blank=True, null=True)),
                ('actions_taken', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AnalyticsData',
        ),
    ]
