# Generated by Django 4.2.6 on 2023-10-17 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitycs', '0002_jsongenerated_viewdata_delete_analyticsdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewdata',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
