# Generated by Django 4.2.6 on 2023-10-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitycs', '0003_alter_viewdata_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateDataAnalitycs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.PositiveBigIntegerField()),
                ('json_generated', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
