# Generated by Django 4.2.6 on 2023-10-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitycs', '0004_generatedataanalitycs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedataanalitycs',
            name='json_generated',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generatedataanalitycs',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
