# Generated by Django 4.2.6 on 2023-10-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitycs', '0005_alter_generatedataanalitycs_json_generated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedataanalitycs',
            name='json_generated',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='generatedataanalitycs',
            name='views',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
