# Generated by Django 4.2.6 on 2023-10-17 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analitycs', '0006_alter_generatedataanalitycs_json_generated_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JsonGenerated',
        ),
        migrations.DeleteModel(
            name='ViewData',
        ),
    ]
